server:
  port: 8080
  servlet:
    context-path: /api/v1.0

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=utf-8
    username: root
    password: Wuqihuan19950903
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

